import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // A leading underscore is this codebase's existing way of saying "this
      // parameter exists to satisfy a signature and is deliberately unread" —
      // a mock's `(_url, _init)`, a destructure that drops a field. Honour the
      // convention rather than reporting each one.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
  // `.codeyam/` holds capture and scenario scripts generated by codeyam-editor,
  // not project source. They are CommonJS by design and are rewritten by the
  // tool, so linting them reports errors nobody can act on.
  globalIgnores([".next/**", "out/**", "build/**", "next-env.d.ts", ".codeyam/**"]),
]);

export default eslintConfig;
